Add missing include to util.h
Fixes:
```bash
mp/util.h:207:20: error: no template named 'function' in namespace 'std'; did you mean 'kj::Function'?
  207 | using FdToArgsFn = std::function<std::vector<std::string>(int fd)>;
      |                    ^~~~~~~~~~~~~
      |                    kj::Function
```
when compiling with libc++ & `_LIBCPP_REMOVE_TRANSITIVE_INCLUDES`.