Fix mptest link error caused by missing kj-async dependency
ld: ../libmultiprocess.a(proxy.cpp.o): in function `mp::EventLoop::EventLoop(char const*, std::function<void (bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)>, void*)':
libmultiprocess/src/mp/proxy.cpp:130: undefined reference to `kj::setupAsyncIo()'
collect2: error: ld returned 1 exit status