Fix $Proxy.wrap mapping for empty structs with no fields
Trying to pass an empty $Proxy.wrap struct with no fields fails because
BuildOne overload for the last field number is incorrectly declared to accept
an lvalue Builder reference instead of a univeral reference, and the
CustomBuildField overload which calls BuildOne passes an rvalue Builder.

The problem did not happen as long as the wrapped struct had at least one field
because CustomBuildField would call the other BuildOne overload for the first
field number which accepts an rvalue Builder, and that BuildOne overload would
call the next BuildOne overload for the next field number, passing the builder
as an lvalue.

A test is included which triggers the bug. Compiler output before the bugfix looked like:

include/mp/proxy-types.h:1066:5: error: no matching function for call to 'BuildOne'
 1066 |     BuildOne<0>(local_type, invoke_context, output.init(), value);

include/mp/proxy-types.h:1050:6: note: candidate function [with index = 0, LocalType = mp::test::FooEmpty, Value = mp::test::FooEmpty, Output = mp::test::messages::FooEmpty::Builder] not viable: expects an lvalue for 3rd argument
 1050 | void BuildOne(TypeList<LocalType> param,